name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    uses: ArwynFr/ArwynFr/.github/workflows/deployment-nuget.yaml@main
    with:
      target: .
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
