name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Java 21 Temurin
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Publish using nuke
        run: ./build.cmd Clean Publish
        env:
          GH_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          NUGET_APIKEY: ${{ secrets.nuget_apikey }}
