name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          clean: 'true'          

      - name: Install Java 21 Temurin
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Verify using nuke
        run: ./build.sh Clean Verify
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
