name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Java version
        run: env | grep "JAVA_HOME"
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}

      - name: Verify using nuke
        run: ./build.sh Clean Verify
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
