name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Test for outdated dependencies
        run: dotnet outdated --fail-on-updates

      - name: Run automated tests
        run: dotnet test ArwynFr.IntegrationTesting.Tests --settings .\runsettings.xml --results-directory TestResults
