name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: SonarCloud configuration
        run: dotnet sonarscanner begin /o:arwynfr /k:ArwynFr_dotnet-integration-testing /d:sonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}

      - name: Run automated tests
        run: dotnet test --settings runsettings.xml --results-directory TestResults
        working-directory: src/ArwynFr.IntegrationTesting.Tests

      - name: SonarCloud analyze
        run: dotnet sonarscanner end

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Check dotnet-format
        run: dotnet format --verify-no-changes

      - name: Check roslynator
        run: dotnet roslynator analyze

      - name: Check markdown
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          dot: true

      - name: Check outdated nuget packages
        run: dotnet outdated --fail-on-updates

      - name: Continuous integration
        run: gh pr merge --squash --auto
        env:
          GH_TOKEN: ${{ github.token }}
